export default [
  {
    startDate: "2026-09",
    institution: "The Hong Kong University of Science and Technology (Guangzhou)",
    degree: "Doctor of Philosophy",
    major: "Computational Media and Arts",
    subAffiliation: "Computational Media and Arts Thrust, Information Hub",
    location: "Guangzhou, China",
    logo: "files/logos/HKUSTGZ Logo Only.svg",
  },
  {
    startDate: "2024-09",
    endDate: "2026-08",
    institution: "The Hong Kong University of Science and Technology (Guangzhou)",
    degree: "Master of Philosophy",
    major: "Computational Media and Arts",
    subAffiliation: "Computational Media and Arts Thrust, Information Hub",
    location: "Guangzhou, China",
    logo: "files/logos/HKUSTGZ Logo Only.svg",
  },
  {
    startDate: "2020-09",
    endDate: "2024-07",
    institution: "South China University of Technology",
    degree: "Bachelor of Engineering",
    major: "Electrical Engineering",
    subAffiliation: "School of Electric Power Engineering",
    location: "Guangzhou, China",
    logo: "files/generated/logos/scut-logo-only.webp",
  },
];
