export default [
  {
    date: "2026-03-25",
    venueKey: "ieee-vr",
    venueText: "IEEE VR 2026",
    venueUrl: "https://ieeevr.org/2026/",
    award: "Best Poster Award",
    text: "Our **DodgeUI** poster received the Best Poster Award at IEEE VR 2026!",
    annotationLeftText: "Sincere thanks to all my collaborators!",
    annotationLeftDirection: "ne",
    annotationRightText: "Appreciated everyone who came by and chatted :)",
    annotationRightDirection: "nw",
    mascot: "files/generated/logos/ieee-vr-26-mascot-sticker.webp",
    mascotAlt: "Sudal-E, the otter mascot of IEEE VR 2026, Daegu, Korea",
  },
  {
    date: "2026-01",
    venueKey: "ieee-vr",
    venueText: "IEEE VR 2026",
    venueUrl: "https://ieeevr.org/2026/",
    text: "One NIDIT Workshop Paper and one Poster are accepted to **IEEE VR 2026**!",
    annotationRightText: "See you at Daegu!",
    annotationRightDirection: "nw",
    mascot: "files/generated/logos/ieee-vr-26-logo-sticker.webp",
    mascotAlt: "IEEE VR 2026, Daegu, Korea",
  },
];
