export default [
  {
    date: "2026-03-20",
    selected: true,
    type: "P",
    venueKey: "ieee-vr",
    venue: "IEEE VR 2026",
    title: "DodgeUI: An Adaptive Interface for Mitigating Attentional Conflict via Implicit Motion Cues in Mobile AR",
    authors: "Yi ZOU, Ao YU, Ziming LI, Hai-Ning LIANG\\*, Pan HUI\\*",
    youtubeUrl: "https://www.youtube.com/watch?v=6GY7u8pQ9s8",
    youtubeLabel: "Presentation Video",
    posterUrl: "files/materials/Poster-1153.pdf",
    doi: "https://doi.org/10.1109/VRW70859.2026.00233",
    award: "Best Poster Award",
  },
  {
    date: "2026-03-20",
    selected: true,
    type: "W",
    workshopLabel: "NIDIT",
    typeLink: "https://sites.google.com/view/nidit/nidit-2026",
    venueKey: "ieee-vr",
    venue: "IEEE VR 2026",
    title: "Contextual Recovery: Guiding Hand Tracking Failures Recovery in Mixed Reality via VLM Reasoning",
    authors: "Yi ZOU, Ziming LI, Hai-Ning LIANG\\*, Zhiming HU\\*",
    youtubeUrl: "https://www.youtube.com/watch?v=ndLDvRxWMRg&t=1s",
    youtubeLabel: "Demo Video",
    doi: "https://doi.org/10.1109/VRW70859.2026.00072",
    slidesUrl: "files/materials/2026.03.22 NIDIT Presentation.pdf",

    // arxivUrl: "https://arxiv.org/",
    // pdfUrl: "files/CV_EN.pdf",
  },
];
